services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - 8000:8000
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: default_password
